import { Router } from "express";
import healthRoutes from "./healthRoutes";
import authRoutes from "./authRoutes";
import userRoutes from "./userRoutes";
import submissionRoutes from "./submissionRoutes";
import contestRoutes from "./contestRoutes";
import leaderboardRoutes from "./leaderboardRoutes";
import gamificationRoutes from "./gamificationRoutes";
import dailyReviewRoutes from "./dailyReviewRoutes";
import studyPlanRoutes from "./studyPlanRoutes";
import goalRoutes from "./goalRoutes";
import recommendationRoutes from "./recommendationRoutes";
import readinessRoutes from "./readinessRoutes";
import analyticsRoutes from "./analyticsRoutes";
import adminRoutes from "./adminRoutes";
import aiRoutes from "./aiRoutes";
import aiGenerationRoutes from "./aiGenerationRoutes";
import uploadRoutes from "./uploadRoutes";
import notificationRoutes from "./notificationRoutes";
import monitoringRoutes from "./monitoringRoutes";
import communityRoutes from "./communityRoutes";
import institutionRoutes from "./institutionRoutes";
import placementRoutes from "./placementRoutes";
import certificateRoutes from "./certificateRoutes";
import searchRoutes from "./searchRoutes";
import recommendationV2Routes from "./recommendationV2Routes";
import judgeRoutes from "./judgeRoutes";
import { adaptiveLearningRoutes } from "./adaptiveLearningRoutes";
import { learningMemoryRoutes } from "./learningMemoryRoutes";
import { companyPrepRoutes } from "./companyPrepRoutes";
import { voiceMentorRoutes } from "./voiceMentorRoutes";
import { collaborationRoutes } from "./collaborationRoutes";
import { careerRoutes } from "./careerRoutes";
import { learningIntelligenceRoutes } from "./learningIntelligenceRoutes";
import { contestRoutes as contestV2Routes } from "./contestRoutes";
import { hiringRoutes } from "./hiringRoutes";
import enterpriseRoutes from "./enterpriseRoutes";
import projectRoutes from "./projectWorkspaceRoutes";
import researchRoutes from "./researchRoutes";
import aiosRoutes from "./aiosRoutes";

const router = Router();

router.use("/research", researchRoutes);
router.use("/aios", aiosRoutes);
router.use("/enterprise", enterpriseRoutes);
router.use("/projects", projectRoutes);
router.use("/hiring", hiringRoutes);
router.use("/contests-v2", contestV2Routes);
router.use("/intelligence", learningIntelligenceRoutes);
router.use("/career", careerRoutes);
router.use("/collaboration", collaborationRoutes);
router.use("/voice", voiceMentorRoutes);
router.use("/company", companyPrepRoutes);
router.use("/memory", learningMemoryRoutes);
router.use("/adaptive", adaptiveLearningRoutes);
router.use("/judge", judgeRoutes);
router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/submissions", submissionRoutes);
router.use("/contests", contestRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/gamification", gamificationRoutes);
router.use("/daily-review", dailyReviewRoutes);
router.use("/study-plans", studyPlanRoutes);
router.use("/goals", goalRoutes);
router.use("/recommendations", recommendationRoutes);
router.use("/recommendations/v2", recommendationV2Routes);
router.use("/readiness", readinessRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/admin", adminRoutes);
router.use("/ai", aiRoutes);
router.use("/ai", aiGenerationRoutes);
router.use("/uploads", uploadRoutes);
router.use("/notifications", notificationRoutes);
router.use("/monitoring", monitoringRoutes);
router.use("/community", communityRoutes);
router.use("/institutions", institutionRoutes);
router.use("/faculty", institutionRoutes);
router.use("/classrooms", institutionRoutes);
router.use("/placements", placementRoutes);
router.use("/certificates", certificateRoutes);
router.use("/search", searchRoutes);

export default router;
